---
- name: "Play to install Zabbix agent on Servers "
  hosts: all
  become: true
  become_user: root
  become_method: sudo
  vars:
    zabbix_server: "X.X.X.X"

  tasks:
    - name: Download Zabbix 4.0 deb file
      get_url:
        url="https://repo.zabbix.com/zabbix/4.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_4.0-2+xenial_all.deb"
        dest="/tmp/zabbix-release_4.0-2.deb"


    - name: Depackaging zabbix .deb file
      apt: deb="/tmp/zabbix-release_4.0-2.deb"

    - name: Updates apt cache
      action: apt update_cache=true

    - name: Apt install Zabbix agent
      apt:
       name: zabbix-agent
       update_cache: yes


    - lineinfile:
       path: /etc/zabbix/zabbix_agentd.conf
       regexp: '^Hostname=Zabbix server'
       line: 'Hostname={{ ansible_hostname }}'
       backrefs: yes

    - lineinfile:
       path: /etc/zabbix/zabbix_agentd.conf
       regexp: '^Server=127.0.0.1'
       line: 'Server={{ zabbix_server }}'
       backrefs: yes


    - name: Restarting zabbix service
      service:
       name: zabbix-agent
       state: restarted
       enabled: yes